# Generated by Django 5.2 on 2025-05-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_wishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='ebay_url',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='user',
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='discord_user_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
