# Generated by Django 5.2 on 2025-05-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0003_remove_wishlistitem_added_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='pokemon',
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='pokemon_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
