# Generated by Django 5.2 on 2025-05-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0004_remove_wishlistitem_pokemon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='card_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='set_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
